version: "3.8"

services:
  front:
    image: nginx:1.19.1-alpine
    container_name: react
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf