version: "3.8"

networks:
  villain-front:

services:
  villain_nginx:
    image: nginx:1.19.1-alpine
    container_name: villain_nginx
    networks:
      - villain-front
    depends_on:
      - villain_react
    ports:
      - "3000:80"
    volumes:
      - static-content:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  villain_react:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - villain-front
    container_name: villain_react
    volumes:
      - static-content:/var/www/html

volumes:
  static-content: