# docker stack deploy -c stack-app.yml app --with-registry-auth --prune
version: "3.7"
services:
  site:
    image: cda56497-kr1-registry.container.cloud.toast.com/villain-front-develop:5
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:80 || exit 1
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 5s
    depends_on:
      - react
    stop_grace_period: 30s
    networks:
      - proxy-main
    deploy:
      placement:
        constraints:
          - node.role == worker
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.develop-react.rule=Host(`develop.villain.school`)"
        - "traefik.http.routers.develop-react.tls=true"
        - "traefik.http.routers.develop-react.tls.certresolver=prod"
        - "traefik.http.routers.develop-react.tls.domains[0].main=*.villain.school"
        - "traefik.http.routers.develop-react.entrypoints=websecure,web"
        - "traefik.http.services.develop-react.loadbalancer.server.port=80"
        - "traefik.http.services.develop-react.loadbalancer.passhostheader=true"
        - "traefik.http.services.develop-react.loadbalancer.healthcheck.path=/"
        - "traefik.http.services.develop-react.loadbalancer.healthcheck.scheme=http"
      resources:
        limits:
          memory: 512MB

networks:
  develop-front:
    external: true
  proxy-main:
    external: true